server:
  port: 3333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761
    fetch-registry: true
    register-with-eureka: true
    
spring:
  cloud:
    gateway:
      routes:
        - id: Welcome-API
           uri:lb://Welcome-API
          predicates:
            - Path=/message
        - id: Greet-API
           uri:lb://Greet-API
          predicates:
            - Path=/Greet

application:
  name: CLOUD-API-GATEWAY


       
      

